In [1]:
import numpy as np
import pandas as pd

In [4]:
#Indices
data=pd.Series([25,17,33,5])
print(data)
print(data.values)
print(data.index)

0    25
1    17
2    33
3     5
dtype: int64
[25 17 33  5]
RangeIndex(start=0, stop=4, step=1)


In [5]:
data=pd.Series([0.75,0.27,0.14,0.33],index=['a','b','c','d'])
data

a    0.75
b    0.27
c    0.14
d    0.33
dtype: float64

In [62]:
area={'Mthatha':54.97,'Butterworth':26.34,'Port Elizabeth':251,'Ugie':19.11}
population={'Mthatha':210783,'Butterworth':44039,'Port Elizabeth':967677,'Ugie':13467}
areas=pd.Series(area)
populations=pd.Series(population)
print(areas)
print(populations)

Mthatha            54.97
Butterworth        26.34
Port Elizabeth    251.00
Ugie               19.11
dtype: float64
Mthatha           210783
Butterworth        44039
Port Elizabeth    967677
Ugie               13467
dtype: int64


In [63]:
town={'area':areas,'population':populations}
towns=pd.DataFrame(town)
towns

area  population
Mthatha          54.97      210783
Butterworth      26.34       44039
Port Elizabeth  251.00      967677
Ugie             19.11       13467

In [9]:
towns['area']

Mthatha            54.97
Butterworth        26.34
Port Elizabeth    251.00
Name: area, dtype: float64

In [10]:
data=pd.DataFrame(np.random.rand(3,3),columns=['foo','boo','koo'],index=['a','b','c'])
data

foo       boo       koo
a  0.877754  0.147387  0.675279
b  0.253341  0.413726  0.198968
c  0.675226  0.800279  0.581768

In [11]:
ind=pd.Index(data=[2,3,7,11])
ind

Int64Index([2, 3, 7, 11], dtype='int64')

In [13]:
print(ind[0])
ind[2::1]

2


Int64Index([7, 11], dtype='int64')

In [21]:
data=pd.Series(np.random.rand(4),index=['a','b','c','d'])
data

a    0.498591
b    0.456447
c    0.598291
d    0.387367
dtype: float64

In [24]:
print(data.keys())
print(data.values)
print(list(data.items()))

Index(['a', 'b', 'c', 'd'], dtype='object')
[0.49859102 0.45644687 0.59829062 0.38736707]
[('a', 0.4985910232659452), ('b', 0.4564468725397426), ('c', 0.598290622578518), ('d', 0.3873670697580539)]


In [26]:
data[(data>=0.3)|(data<0.5)]

a    0.498591
b    0.456447
c    0.598291
d    0.387367
dtype: float64

In [27]:
data=pd.Series(data=[3,5,7,9],index=[1,2,3,4])
data

1    3
2    5
3    7
4    9
dtype: int64

In [32]:
data[1] #Indexing explicit

3

In [34]:
data[2:] #Slicing implicit

3    7
4    9
dtype: int64

In [40]:
#explicit indexing and slicing
print(data.loc[1])
print(data.loc[3:])

3
3    7
4    9
dtype: int64


In [47]:
#implicit indexing and slicing
print(data.iloc[0])
print(data.iloc[3:])

3
4    9
dtype: int64


In [48]:
towns['area']

Mthatha            54.97
Butterworth        26.34
Port Elizabeth    251.00
Name: area, dtype: float64

In [64]:
towns['density']=towns['population']/towns['area']
towns

area  population      density
Mthatha          54.97      210783  3834.509733
Butterworth      26.34       44039  1671.943812
Port Elizabeth  251.00      967677  3855.286853
Ugie             19.11       13467   704.709576

In [65]:
towns.values

array([[5.49700000e+01, 2.10783000e+05, 3.83450973e+03],
       [2.63400000e+01, 4.40390000e+04, 1.67194381e+03],
       [2.51000000e+02, 9.67677000e+05, 3.85528685e+03],
       [1.91100000e+01, 1.34670000e+04, 7.04709576e+02]])

In [66]:
towns.values[0][0]

54.97

In [67]:
towns

area  population      density
Mthatha          54.97      210783  3834.509733
Butterworth      26.34       44039  1671.943812
Port Elizabeth  251.00      967677  3855.286853
Ugie             19.11       13467   704.709576

In [78]:
towns.iloc[1:3]

area  population      density
Butterworth      26.34       44039  1671.943812
Port Elizabeth  251.00      967677  3855.286853

In [89]:
towns.loc[towns['area']<50]

area  population      density
Butterworth  26.34       44039  1671.943812
Ugie         19.11       13467   704.709576

In [93]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape
planets.tail()

method  number  orbital_period  mass  distance  year
1030  Transit       1        3.941507   NaN     172.0  2006
1031  Transit       1        2.615864   NaN     148.0  2007
1032  Transit       1        3.191524   NaN     174.0  2007
1033  Transit       1        4.125083   NaN     293.0  2008
1034  Transit       1        4.187757   NaN     260.0  2008

In [94]:
df=pd.DataFrame(data={'a':np.random.rand(5),'b':np.random.rand(5)})
print(df.head())

          a         b
0  0.501473  0.513465
1  0.650545  0.983404
2  0.899120  0.688815
3  0.467273  0.768577
4  0.229688  0.258992


In [95]:
df.mean()

a    0.549620
b    0.642651
dtype: float64

In [96]:
df.mean(axis='columns')

0    0.507469
1    0.816975
2    0.793967
3    0.617925
4    0.244340
dtype: float64

In [103]:
planets.dropna().describe().iloc[0][0]

498.0

In [104]:
data=pd.DataFrame(data={'key':['A','B','C','A','B','C'],'data':range(6)})
data

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [105]:
data.groupby('key')

In [106]:
data.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [108]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [109]:
planets.groupby('method')

In [110]:
planets.groupby('method')['orbital_period']

In [111]:
planets.groupby('method')['orbital_period'].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [112]:
planets.groupby('method').mean()

number  orbital_period      mass  \
method                                                              
Astrometry                     1.000000      631.180000       NaN   
Eclipse Timing Variations      1.666667     4751.644444  5.125000   
Imaging                        1.315789   118247.737500       NaN   
Microlensing                   1.173913     3153.571429       NaN   
Orbital Brightness Modulation  1.666667        0.709307       NaN   
Pulsar Timing                  2.200000     7343.021201       NaN   
Pulsation Timing Variations    1.000000     1170.000000       NaN   
Radial Velocity                1.721519      823.354680  2.630699   
Transit                        1.954660       21.102073  1.470000   
Transit Timing Variations      2.250000       79.783500       NaN   

                                  distance         year  
method                                                   
Astrometry                       17.875000  2011.500000  
Eclipse Timing Variations       315.360000  2010.000000  
Imaging                          67.715937  2009.131579  
Microlensing                   4144.000000  2009.782609  
Orbital Brightness Modulation  1180.000000  2011.666667  
Pulsar Timing                  1200.000000  1998.400000  
Pulsation Timing Variations            NaN  2007.000000  
Radial Velocity                  51.600208  2007.518987  
Transit                         599.298080  2011.236776  
Transit Timing Variations      1104.333333  2012.500000

In [128]:
for (m,l) in planets.groupby('method'):
    print("{0}".format(l))

         method  number  orbital_period  mass  distance  year
113  Astrometry       1          246.36   NaN     20.77  2013
537  Astrometry       1         1016.00   NaN     14.98  2010
                       method  number  orbital_period  mass  distance  year
32  Eclipse Timing Variations       1        10220.00  6.05       NaN  2009
37  Eclipse Timing Variations       2         5767.00   NaN    130.72  2008
38  Eclipse Timing Variations       2         3321.00   NaN    130.72  2008
39  Eclipse Timing Variations       2         5573.55   NaN    500.00  2010
40  Eclipse Timing Variations       2         2883.50   NaN    500.00  2010
41  Eclipse Timing Variations       1         2900.00   NaN       NaN  2011
42  Eclipse Timing Variations       1         4343.50  4.20       NaN  2012
43  Eclipse Timing Variations       2         5840.00   NaN       NaN  2011
44  Eclipse Timing Variations       2         1916.25   NaN       NaN  2011
       method  number  orbital_period  mass  distance 

In [147]:
data={'key':['a','b','c','a','b','c'],
        'data1':range(6),
        'data2':np.random.randint(0,10,6)}
df=pd.DataFrame(data=data)
df

key  data1  data2
0   a      0      7
1   b      1      3
2   c      2      2
3   a      3      2
4   b      4      8
5   c      5      8

In [149]:
df.groupby('key').aggregate(['min','mean','max','sum'])

data1              data2             
      min mean max sum   min mean max sum
key                                      
a       0  1.5   3   3     2  4.5   7   9
b       1  2.5   4   5     3  5.5   8  11
c       2  3.5   5   7     2  5.0   8  10

In [150]:
df.groupby('key').aggregate({'key':'count','data1':'min','data2':'max'})

key  data1  data2
key                   
a      2      0      7
b      2      1      8
c      2      2      8

In [157]:
def filter_max(df:pd.DataFrame):
    return df['data2'].max()==8

def equal_val(df:pd.DataFrame):
    return df['data2'].__contains__(8)

df.groupby('key').filter(filter_max)


key  data1  data2
1   b      1      3
2   c      2      2
4   b      4      8
5   c      5      8

In [158]:
print(filter_max(df))
print(equal_val(df))

True
False
